name: Android Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Grant execute permissions for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      id: build
      run: ./gradlew build
      
    - name: Run unit tests with coverage
      id: unit_tests
      if: success() && steps.build.outcome == 'success'
      run: ./gradlew test jacocoTestReport
      
    - name: Enable KVM group perms
      if: success() && steps.unit_tests.outcome == 'success'
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
        
    - name: Set up Android SDK
      if: success() && steps.unit_tests.outcome == 'success'
      uses: android-actions/setup-android@v3
      
    - name: AVD cache
      if: success() && steps.unit_tests.outcome == 'success'
      uses: actions/cache@v4
      id: avd-cache
      with:
        path: |
          ~/.android/avd/*
          ~/.android/adb*
        key: avd-29
        
    - name: Create AVD and generate snapshot for caching
      if: success() && steps.unit_tests.outcome == 'success' && steps.avd-cache.outputs.cache-hit != 'true'
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 34
        target: google_apis
        arch: x86_64
        profile: pixel
        force-avd-creation: false
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: false
        script: echo "Generated AVD snapshot for caching."
        
    - name: Run integration tests
      id: integration_tests
      if: success() && steps.unit_tests.outcome == 'success'
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 34
        target: google_apis
        arch: x86_64
        profile: pixel
        force-avd-creation: false
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: true
        script: ./gradlew connectedAndroidTest
      
    - name: Upload coverage report
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: app/build/reports/jacoco/
        
    - name: Upload integration test results
      if: always() && steps.integration_tests.outcome != 'skipped'
      uses: actions/upload-artifact@v4
      with:
        name: integration-test-results
        path: |
          app/build/reports/androidTests/
          app/build/outputs/androidTest-results/
